//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTDocumentLocation, DVTFilePath, IDESourceKitSymbol, IDESourceKitWorkspace, NSURL;

@interface IDESourceKitSymbolOccurrence : NSObject
{
    long long _role;	// 8 = 0x8
    DVTDocumentLocation *_location;	// 16 = 0x10
    long long _lineNumber;	// 24 = 0x18
    long long _column;	// 32 = 0x20
    DVTFilePath *_file;	// 40 = 0x28
    NSURL *_moduleURL;	// 48 = 0x30
    IDESourceKitSymbol *_correspondingSymbol;	// 56 = 0x38
    IDESourceKitSymbol *_containingSymbol;	// 64 = 0x40
    IDESourceKitWorkspace *_index;	// 72 = 0x48
}

@property(readonly, nonatomic) long long column; // @synthesize column=_column;
@property(readonly, nonatomic) long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property(readonly, nonatomic) long long role; // @synthesize role=_role;
//- (void).cxx_destruct;
- (BOOL)isKindOfClass:(Class)arg1;
- (id)callees;
@property(readonly, nonatomic) DVTDocumentLocation *location;
@property(readonly, nonatomic) NSURL *moduleURL;
@property(readonly, nonatomic) DVTFilePath *file;
- (id)index;
- (id)occurrence;
- (void)setContainingSymbol:(id)arg1;
- (id)containingSymbol;
- (id)description;
- (void)setOccurrence:(id)arg1;
- (id)correspondingSymbol;
- (id)initWithCorrespondingSymbol:(id)arg1 role:(long long)arg2 lineNumber:(long long)arg3 column:(long long)arg4 file:(id)arg5 location:(id)arg6 moduleURL:(id)arg7 forSourceKitWorkspace:(id)arg8;
- (void)describeFields:(CDUnknownBlockType)arg1;

@end

