//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


@class DVTTextDocumentLocation, NSString;

@protocol IDESourceCodeDocument <NSObject>
- (DVTTextDocumentLocation *)documentLocation:(DVTTextDocumentLocation *)arg1 byUnion:(DVTTextDocumentLocation *)arg2;
- (DVTTextDocumentLocation *)documentLocationWithEnclosingLineRangeAtLocation:(DVTTextDocumentLocation *)arg1;
- (DVTTextDocumentLocation *)documentLocationWithLastLineRangeAtLocation:(DVTTextDocumentLocation *)arg1;
- (BOOL)hasMultiLineAnnotationHighlight;
- (DVTTextDocumentLocation *)insertCharactersAfterLocation:(DVTTextDocumentLocation *)arg1 withString:(NSString *)arg2;
- (DVTTextDocumentLocation *)insertCharactersBeforeLocation:(DVTTextDocumentLocation *)arg1 withString:(NSString *)arg2;
- (DVTTextDocumentLocation *)replaceCharactersAtLocation:(DVTTextDocumentLocation *)arg1 withString:(NSString *)arg2;
@end

